#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmMobile.Sample.Droid.Resource", IsApplication=true)]

namespace MvvmMobile.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmMobile.Droid.Resource.Id.fragmentContainer = global::MvvmMobile.Sample.Droid.Resource.Id.fragmentContainer;
			global::MvvmMobile.Droid.Resource.Layout.FragmentContainerActivityLayout = global::MvvmMobile.Sample.Droid.Resource.Layout.FragmentContainerActivityLayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int accent = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int black = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int darkGray = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int divider = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int gray = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int icons = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int lightGray = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primary_dark = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int primary_light = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int primary_text = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int red = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int secondary_text = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int white = 2130968585;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int brandEditText = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int deleteButton = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int fragmentContainer = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int listView = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int mainLayout = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int menuAdd = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int menuDone = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int modelEditText = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int titleTextView = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int yearEditText = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditMotorcycleLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentContainerActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int StartActivityItemLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int StartActivityLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int EditMotorcycleActivityMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int StartActivityMenu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int add = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int delete = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int done = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int motorcycle = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int motorcycles = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
