#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmMobile.Sample.Droid.Resource", IsApplication=true)]

namespace MvvmMobile.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmMobile.Droid.Resource.Id.fragmentContainer = global::MvvmMobile.Sample.Droid.Resource.Id.fragmentContainer;
			global::MvvmMobile.Droid.Resource.Layout.FragmentContainerActivityLayout = global::MvvmMobile.Sample.Droid.Resource.Layout.FragmentContainerActivityLayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int button = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int firstButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int fragmentContainer = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int secondButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int titleTextView = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentContainerActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SecondActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int StartActivityLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
