#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmMobile.Sample.Droid.Resource", IsApplication=true)]

namespace MvvmMobile.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmMobile.Droid.Resource.Id.fragmentContainer = global::MvvmMobile.Sample.Droid.Resource.Id.fragmentContainer;
			global::MvvmMobile.Droid.Resource.Layout.FragmentContainerActivityLayout = global::MvvmMobile.Sample.Droid.Resource.Layout.FragmentContainerActivityLayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060003
			public const int accent = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int black = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int darkGray = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int divider = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int gray = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int icons = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int lightGray = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int primary = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int primary_light = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int primary_text = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int red = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int secondary_text = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int white = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070006
			public const int elevation_fab = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int elevation_toolbar = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int margin_normal = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int spacing_double = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int spacing_huge = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int spacing_micro = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int spacing_normal = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ripple_with_white_background = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0000
			public const int brandEditText = 2131492864;
			
			// aapt resource value: 0x7f0c0004
			public const int deleteButton = 2131492868;
			
			// aapt resource value: 0x7f0c0003
			public const int fragmentContainer = 2131492867;
			
			// aapt resource value: 0x7f0c0007
			public const int listView = 2131492871;
			
			// aapt resource value: 0x7f0c0005
			public const int mainLayout = 2131492869;
			
			// aapt resource value: 0x7f0c000a
			public const int menuAdd = 2131492874;
			
			// aapt resource value: 0x7f0c0009
			public const int menuDone = 2131492873;
			
			// aapt resource value: 0x7f0c0001
			public const int modelEditText = 2131492865;
			
			// aapt resource value: 0x7f0c0006
			public const int titleTextView = 2131492870;
			
			// aapt resource value: 0x7f0c0008
			public const int toolbar = 2131492872;
			
			// aapt resource value: 0x7f0c0002
			public const int yearEditText = 2131492866;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int transition_anim_duration = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int EditMotorcycleLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FragmentContainerActivityLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int StartActivityItemLayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int StartActivityLayout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Toolbar = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int EditMotorcycleActivityMenu = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int StartActivityMenu = 2131427329;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090003
			public const int add = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int delete = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int done = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int motorcycle = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int motorcycles = 2131296257;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0003
			public const int EditTextStyle = 2131361795;
			
			// aapt resource value: 0x7f0a0002
			public const int fieldLabelTextView = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int standardTextView = 2131361793;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Transition
		{
			
			// aapt resource value: 0x7f050000
			public const int fade = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide = 2131034113;
			
			static Transition()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Transition()
			{
			}
		}
	}
}
#pragma warning restore 1591
